from marshmallow import fields, validate
from schemas import ma

# Define the product 
class ProductSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    name = fields.String(required=True)
    price = fields.Float(required=True, validate=validate.Range(min=0))
    stock_quantity = fields.Integer(required=True, validate=validate.Range(min=0))

    class Meta:
        fields = ("id", "name", "price", "stock_quantity")

class ProductIdSchema(ma.Schema):
    id = fields.Integer(required=True)

# Create instances of the schema
product_schema = ProductSchema()
products_schema = ProductSchema(many=True)