from marshmallow import fields
from schemas import ma

# Define the shopping cart 
class ShoppingCartSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    customer_id = fields.Integer(required=True)
    products = fields.Nested("ProductIdSchema", many=True)

# Create instances of the schema
shopping_cart_schema = ShoppingCartSchema()
shopping_carts_schema = ShoppingCartSchema(many=True)